#! /bin/bash

usage() {
    echo 'Usage: bigfile-repartition file block Nfile' >&2
    exit;
}

fail () {
    exit;
}
ROOT=`dirname $0`

$ROOT/bigfile-rename $1 $2 $2-REPBAK || fail
$ROOT/bigfile-copy -n $3 $1 $2-REPBAK $2 ||fail
$ROOT/bigfile-rm $1 $2-REPBAK ||fail

